const NEXT_PUBLIC_API_KEY = 'api_key'
const NEXT_PUBLIC_AUTH_DOMAIN = 'auth_domain'
const NEXT_PUBLIC_PROJECT_ID = 'project_id'
const NEXT_PUBLIC_STORAGE_BUCKET = 'storage_bucket'
const NEXT_PUBLIC_MESSAGING_SENDER_ID = 'message_sender_id'
const NEXT_PUBLIC_APP_ID = 'app_id'

export {
  NEXT_PUBLIC_API_KEY,
  NEXT_PUBLIC_AUTH_DOMAIN,
  NEXT_PUBLIC_PROJECT_ID,
  NEXT_PUBLIC_STORAGE_BUCKET,
  NEXT_PUBLIC_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_APP_ID,
}
