name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 2223:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: psqluser
          POSTGRES_DB: frouriopfl
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        id: client-yarn-cache
        with:
          path: 'node_modules'
          key: client-yarn-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v3
        id: server-yarn-cache
        with:
          path: 'server/node_modules'
          key: server-yarn-${{ hashFiles('server/yarn.lock') }}

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE_TEST_CLIENT }}" > ./.env
          echo "${{ secrets.ENV_FILE_TEST_SERVER }}" > ./server/.env
          echo "${{ secrets.ENV_FILE_TEST_DB }}" > ./server/prisma/.env

      - run: yarn install
        if: steps.client-yarn-cache.outputs.cache-hit != 'true'
      - run: yarn install --cwd server
        if: steps.server-yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint
      - run: yarn typecheck
      - run: |
          yarn migrate:dev
          yarn test:unit
          yarn test:integration
        env:
          API_JWT_SECRET: test_secret
